name: Build CodeView

on:
  workflow_dispatch:  # รันด้วยมือผ่านหน้า GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ติดตั้ง Java 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: ดาวน์โหลด CodeView 1.3.9
        run: |
          curl -L -o codeview.zip https://github.com/AmrDeveloper/CodeView/archive/refs/tags/1.3.9.zip

      - name: แตกไฟล์ zip
        run: unzip codeview.zip

      - name: รัน Gradle build
        run: |
          cd CodeView-1.3.9
          bash ./gradlew build
