name: Java CI (with git clone)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
       - name: Java
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Clone CodeView library
        run: |
          git clone https://github.com/tiagohm/CodeView.git codeview
          ls -l

      - name: Build CodeView
        run: |
          cd codeview
          chmod +x ./gradlew
          ./gradlew build
