name: Java CI (with git clone)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo หลักของคุณ
      - uses: actions/checkout@v4

      # โคลน CodeView โดยใช้ git clone เอง
      - name: Clone CodeView library
        run: |
          git clone https://github.com/tiagohm/CodeView.git codeview

      # ตั้งค่า JDK (ตัวอย่างนี้ใช้ JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # รัน Gradle ด้วย bash
      - name: Build with Gradle
        run: bash ./gradlew build
