name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo หลักของคุณ
      - uses: actions/checkout@v4

      # Checkout ไลบรารี CodeView เพิ่มเข้ามา (อยู่ในโฟลเดอร์ codeview)
      - name: Checkout CodeView library
        uses: actions/checkout@v4
        with:
          repository: tiagohm/CodeView
          ref: master
          path: codeview

      # ตั้งค่า JDK (ตัวอย่างนี้ใช้ JDK 17)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # สั่ง build ด้วย Gradle (เปลี่ยนเป็น mvn ถ้าใช้ Maven)
      - name: Build with Gradle
        run: ./gradlew build
