name: Build CodeView

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: ติดตั้ง Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ดาวน์โหลด CodeView 1.3.9
        run: |
          curl -L -o codeview.zip https://github.com/AmrDeveloper/CodeView/archive/refs/tags/1.3.9.zip

      - name: แตกไฟล์ zip
        run: unzip codeview.zip

      - name: รัน Gradle build
        run: |
          cd CodeView-1.3.9
          chmod +x ./gradlew
          ./gradlew build

      - name: ตรวจสอบไฟล์ทั้งหมดหลัง build
        run: |
          echo "==== แสดงรายการไฟล์ทั้งหมดใน CodeView-1.3.9 ===="
          find ./CodeView-1.3.9 -type f

      - name: อัปโหลด build artifact (AAR)
        uses: actions/upload-artifact@v4
        with:
          name: CodeView-built-aar
          path: ./CodeView-1.3.9/library/build/outputs/aar/
