name: Build CodeView Library

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CodeView source
        uses: actions/checkout@v4
        with:
          repository: AmrDeveloper/CodeView
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build CodeView library (AAR)
        run: ./gradlew :codeview:assembleRelease

      - name: Upload AAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: codeview-aar
          path: codeview/build/outputs/aar/*.aar
